### ISSUE TITLE
Make Module Installable Via Composer

### ISSUE THREAD

**Issue by NathanDayMF** [CompactCodeEU/FixProductBreadcrumbs#1]
## Background
As a Developer I would like to be able to install this Module via Composer

## UAC
- [ ] Module is install by composer

## Suggested fix
- move `composer.json` file to repository root
- change `FixProductBreadcrumbs` directory name to `src`
- modify `composer.json` 
	- line 21 to be `"src/registration.php"'
	- line 24 to be `"CompactCode\\FixProductBreadcrumbs\\": "src"`
	- Remove `"extra"` array (line 27 - 34)
- Update Readme with Composer Install Instructions
 
```BASH
## Composer Install Instructions
composer config repositories.compact-code-fix-product-breadcrumbs git git@github.com:CompactCodeEU/FixProductBreadcrumbs.git
composer require compactcode/fixproductbreadcrumbs: "dev-master"
php bin/magento setup:upgrade
```

**Comment by CompactCodeEU** [comment]
@NathanDayMF Sure no problem. I will complete this task today.

**Comment by CompactCodeEU** [comment]
@NathanDayMF Can you comfirm that this is correct now?

**Comment by andrsan** [comment]
tried installing but gives an error:

```
Skipped branch master, "'a7fd4225ada0e1b556a4c67d0bce851f4031dfa0':composer.json" does not contain valid JSON
Parse error on line 26:
}   },     }
-------------------^
Expected: 'STRING' - It appears you have an extra trailing comma
  [Composer\Repository\InvalidRepositoryException]
  No valid composer.json was found in any branch or tag of git@github.com:CompactCodeEU/FixProductBreadcrumbs.git, could not load a package from it.

```

can you check it out?
thank you

**Comment by CompactCodeEU** [comment]
Should be fixed now

**Comment by andrsan** [comment]
Not yet!
I've made a pull request with the proposed fixes.
Thank you.

**Comment by CompactCodeEU** [comment]
Ok i see. Thanks for the help! I accepted the pull request. I will close this. If any problems still occur please open a new issue. Again thanks for the help.
